# create new repository
POST http://localhost:8000/repo/ HTTP/1.1
Content-Type:  application/json

{
    "name" : "testRepo2",
    "description" : "this is test repo1 of user1",
    "visibility" : true,
    "userId" : "6a1600804b7cf14fede621b1"
}

###

# get all repositories
GET  http://localhost:8000/repo/ HTTP/1.1
Content-Type:  application/json


###

# get repository by name
GET  http://localhost:8000/repo/name/testRepo2 HTTP/1.1
Content-Type:  application/json


###


# get repositories by userid
GET  http://localhost:8000/repo/user/6a1600804b7cf14fede621b1 HTTP/1.1
Content-Type:  application/json


###

# get repository by repoid
GET  http://localhost:8000/repo/6a1604c3e9e176b58a64cc0d HTTP/1.1
Content-Type:  application/json


###

# update repository 
PUT  http://localhost:8000/repo/6a1604c3e9e176b58a64cc0d HTTP/1.1
Content-Type:  application/json

{
    "name" : "updated name",
    "description" : "updated description",
    "content" : "updated content"
}

###

# Delete repository 
DELETE   http://localhost:8000/repo/6a1604c3e9e176b58a64cc0d HTTP/1.1
Content-Type:  application/json


###

# Delete repository 
PATCH    http://localhost:8000/repo/visibility/6a1603fe8e99f2cb12557c99 HTTP/1.1
Content-Type:  application/json


###